theme: jekyll-theme-cayman
title: Ishanvi Patel
description: [I am an incoming junior at Del Norte High School. I am interested in biochemistry and genetics as well as their applications to help save lives. In the future, I hope my work inspires more women in STEM and helps increase medical equity. ]

